<script setup>
import { ref, computed, onMounted, onUnmounted, nextTick, watch } from 'vue';
import { Sprout, LayoutDashboard, MessageSquare, GitCompareArrows, Library, FlaskConical, Network, ChevronDown, ChevronRight, Plus, ArrowUpRight, Search, Bell, CircleHelp, Upload, Download, FileText, Check, Clock3, X, Send, Sparkles, Database, Server, ShieldCheck, MoreHorizontal, CheckCheck, Menu, SlidersHorizontal, ExternalLink, Activity, RotateCcw, Cpu, Cable, CircleAlert, SquarePen } from 'lucide-vue-next';
import { initialDocs } from './data';
import { api } from './api';
import Pipeline from './Pipeline.vue';

const nav = [{id:'overview',label:'工作台',icon:LayoutDashboard},{id:'chat',label:'农业问答',icon:MessageSquare},{id:'reviews',label:'双模型评审',icon:GitCompareArrows},{id:'knowledge',label:'知识资料',icon:Library},{id:'training',label:'模型训练',icon:FlaskConical},{id:'gateway',label:'模型中转',icon:Network}];
const route = ref(nav.some(n=>n.id===location.hash.slice(1))?location.hash.slice(1):'overview');
const mobileMenu=ref(false), toast=ref(''), dialog=ref(''), query=ref(''), filter=ref('全部'), period=ref('近 7 天');
const tasks=ref([]), docs=ref(structuredClone(initialDocs));
const pipelinePairId=ref('');
const selected=ref(null), decision=ref(''), note=ref(''), finalAnswer=ref(''), reveal=ref(false), tab=ref('待评审');
const uploadFiles=ref([]), uploadDomain=ref('种植管理'), fileInput=ref(null), uploadError=ref('');
const provider=ref('兼容接口'), baseUrl=ref(''), modelName=ref(''), settingsSaved=ref(false), settingsError=ref('');
let timer;
const modelStatus=ref([]);
async function loadModels(){try{modelStatus.value=(await api.models()).models}catch{modelStatus.value=[]}}
const events=ref([{title:'真实评审数据本地保存',detail:'SQLite · 问答、修订与复审',time:'v0.2'},{title:'人工选择前隐藏裁判',detail:'先独立判断，再对照 AI 意见',time:'v0.2'},{title:'等待 DGX 训练接入',detail:'训练与设备控制尚未执行',time:'规划'}]);
const pending=computed(()=>tasks.value.filter(t=>t.status==='待评审'));
const checked=computed(()=>tasks.value.filter(t=>t.status==='已审核'));
const visibleTasks=computed(()=>tasks.value.filter(t=>(tab.value==='全部'||t.status===tab.value)&&(!query.value||t.title.includes(query.value))));
const visibleDocs=computed(()=>docs.value.filter(d=>(filter.value==='全部'||d.domain===filter.value)&&(!query.value||d.name.toLowerCase().includes(query.value.toLowerCase()))));
const title=computed(()=>nav.find(n=>n.id===route.value)?.label||'工作台');
function notify(text){toast.value=text;clearTimeout(timer);timer=setTimeout(()=>toast.value='',3500)}
function go(id){if(!['chat','reviews'].includes(id))pipelinePairId.value='';route.value=id;location.hash=id;mobileMenu.value=false;query.value='';filter.value='全部';selected.value=null}
function hashChange(){const id=location.hash.slice(1);if(nav.some(n=>n.id===id)){route.value=id;selected.value=null;query.value=''}}
function log(title,detail){events.value.unshift({title,detail,time:'刚刚'})}
function updateTasks(rows){const status={unreviewed:'待评审',pending:'待评审',awaiting_review:'待复审',approved:'已审核',excluded:'已排除'};tasks.value=rows.map(r=>({id:r.id,title:r.question,question:r.question,domain:'农业案例',crop:r.split==='eval'?'评测组':'训练候选',status:status[r.review_status],date:r.created_at}));}
async function loadTasks(){try{updateTasks((await api.comparisons()).items)}catch{/* Main workflow displays actionable connection errors. */}}
function review(t){pipelinePairId.value=t.id;go('reviews')}
function newChat(){pipelinePairId.value='';go('chat')}
function toggleMode(){go('chat')}
function download(content,name,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportData(){pipelinePairId.value='';go('reviews');notify('在专家数据工作台选择正式导出类型')}
function handleFiles(e){uploadFiles.value=[...(e.target.files||[])];uploadError.value=''}
function registerFiles(){if(!uploadFiles.value.length){uploadError.value='请先选择文件';return}if(uploadFiles.value.some(f=>f.size>20*1024*1024)){uploadError.value='单个文件不能超过 20 MB';return}if(uploadFiles.value.some(f=>!/\.(pdf|docx|txt)$/i.test(f.name))){uploadError.value='仅支持 PDF、DOCX、TXT 文件';return}for(const f of uploadFiles.value)docs.value.unshift({id:`DOC-${Date.now()}-${f.name}`,name:f.name,type:f.name.split('.').pop().toUpperCase(),domain:uploadDomain.value,size:f.size>1024*1024?`${(f.size/1024/1024).toFixed(1)} MB`:`${Math.ceil(f.size/1024)} KB`,status:'待接入上传服务',date:new Date().toISOString().slice(0,10),source:'本次会话 · 仅文件信息'});log('登记资料信息',`${uploadFiles.value.length} 个文件，原文件未上传`);dialog.value='';uploadFiles.value=[];notify('已登记文件信息；原文件未上传，未解析入库')}
function saveConfig(){try{const u=new URL(baseUrl.value);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.search||u.hash)throw Error();if(!modelName.value.trim())throw Error();settingsError.value='';settingsSaved.value=true;notify('配置草稿已保留在本次会话，尚未连接供应商')}catch{settingsError.value='请填写有效的 HTTP(S) 地址和模型名称，地址不要包含凭证、查询参数或锚点。'}}
function exportConfig(){if(!settingsSaved.value){notify('请先校验并保存配置草稿');return}download(JSON.stringify({demo_config:true,models:{cloud_primary:{adapter:provider.value==='兼容接口'?'openai_compatible':'vendor_native',base_url:baseUrl.value,model:modelName.value,credential_ref:'CLOUD_PRIMARY_API_KEY'}}},null,2),'model-gateway.example.json')}
function openDialog(name){dialog.value=name;uploadError.value=''}
let previousFocus;
watch(dialog,async(value,old)=>{if(value&&!old){previousFocus=document.activeElement;await nextTick();document.querySelector('.modal button')?.focus()}else if(!value){previousFocus?.focus()}});
function escape(e){if(e.key==='Escape'){dialog.value='';mobileMenu.value=false}if(e.key==='Tab'&&dialog.value){const items=[...document.querySelectorAll('.modal button:not([disabled]), .modal input:not([hidden]), .modal select, .modal textarea')].filter(el=>el.offsetParent!==null);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}
onMounted(()=>{loadTasks();loadModels();window.addEventListener('hashchange',hashChange);window.addEventListener('keydown',escape);const ctx=document.modelContext;if(ctx?.registerTool)Promise.resolve(ctx.registerTool({name:'navigate_agri_workspace',description:'打开农业工作台中的一个页面，不提交数据。',inputSchema:{type:'object',properties:{page:{type:'string',enum:nav.map(n=>n.id)}},required:['page'],additionalProperties:false},execute(input){if(!nav.some(n=>n.id===input.page))throw new Error('未知页面');go(input.page);return {page:route.value}},annotations:{readOnlyHint:true}})).catch(()=>{})});
onUnmounted(()=>{window.removeEventListener('hashchange',hashChange);window.removeEventListener('keydown',escape);clearTimeout(timer);});
</script>

<template>
<div class="app-shell">
 <div v-if="mobileMenu" class="sidebar-shade" @click="mobileMenu=false"></div>
 <aside class="sidebar" :class="{open:mobileMenu}">
  <a href="#overview" class="brand" @click.prevent="go('overview')"><span class="brand-mark"><Sprout :size="25"/></span><span>青禾 <small>AGRI INTELLIGENCE</small></span></a>
  <button class="workspace-switch" @click="openDialog('workspace')"><span class="workspace-symbol">禾</span><span>农业 AI 工作空间<small>208 亩示范园区</small></span><ChevronDown :size="15"/></button>
  <div class="nav-caption">工作空间</div>
  <nav aria-label="主导航"><button v-for="item in nav" :key="item.id" :class="['nav-item',{active:route===item.id}]" @click="go(item.id)"><component :is="item.icon" :size="19"/><span>{{item.label}}</span><span v-if="item.id==='reviews'&&pending.length" class="nav-count">{{pending.length}}</span></button></nav>
  <div class="sidebar-bottom"><div class="phase-card"><div><span class="tiny-square"></span> 第一阶段 · AI 数据闭环</div><p>从专业经验，到农业智能。</p><div class="phase-line"><i></i></div><span>当前版本：本地数据工作台</span></div><button class="help-link" @click="openDialog('help')"><CircleHelp :size="18"/>使用说明<span>↗</span></button><div class="profile"><span class="avatar">农</span><div>园区管理员<small>本机试用 · 尚未登录</small></div><button aria-label="查看账户说明" @click="openDialog('workspace')"><MoreHorizontal :size="19"/></button></div></div>
 </aside>
 <div class="main-shell">
  <header class="topbar"><div class="breadcrumb"><button class="mobile-trigger" aria-label="打开菜单" @click="mobileMenu=true"><Menu :size="22"/></button><span>农业 AI 平台</span><ChevronRight :size="14"/><strong>{{title}}</strong></div><div class="top-actions"><button class="demo-pill" @click="toggleMode" aria-label="打开真实问答">本地数据版</button><span class="top-divider"></span><button aria-label="查看通知" @click="openDialog('notifications')"><Bell :size="19"/><span class="notification-dot"></span></button><button class="top-avatar" aria-label="账户信息" @click="openDialog('workspace')">农</button></div></header>
  <main>
   <template v-if="route==='overview'">
    <section class="page-heading"><div><div class="eyebrow">WORKSPACE OVERVIEW</div><h1>让每一份农业经验，成为智能的养分。</h1><p>从问答到评审，从知识到训练，在这里建立你的农业 AI 数据闭环。</p></div><button class="primary" @click="newChat"><Plus :size="18"/>发起农业问答</button></section>
    <div class="notice"><span><CircleAlert :size="16"/>问答与评审已本地持久化；知识目录、趋势图与训练页面仍为演示。</span><button @click="openDialog('help')">了解当前版本 <ChevronRight :size="14"/></button></div>
    <section class="stats-grid">
     <article class="stat"><div><span>农业问答</span><MessageSquare :size="19"/></div><strong>{{tasks.length}}<small>次</small></strong><p>数据库中的真实问题<span class="subtle-tag">当前</span></p></article>
     <article class="stat"><div><span>待专家评审</span><GitCompareArrows :size="19"/></div><strong>{{pending.length}}<small>条</small></strong><p>等待专业判断与修订<button @click="go('reviews')">去处理 <ArrowUpRight :size="14"/></button></p></article>
     <article class="stat"><div><span>知识资料</span><Library :size="19"/></div><strong>{{docs.length}}<small>份</small></strong><p>示例与本次登记的资料<span class="subtle-tag">含示例</span></p></article>
     <article class="stat"><div><span>已审核样本</span><Database :size="19"/></div><strong>{{checked.length}}<small>条</small></strong><p>复审通过，按规则导出<span class="subtle-tag">真实</span></p></article>
    </section>
    <div class="overview-grid">
     <section class="panel review-panel"><div class="panel-heading"><div><h2>待办评审 <span class="count-label">{{pending.length}}</span></h2><p>专业判断，是模型成长的第一步。</p></div><button class="text-button" @click="go('reviews')">全部任务 <ChevronRight :size="15"/></button></div><div class="task-list"><div v-for="t in pending.slice(0,3)" :key="t.id" class="task-row"><span class="task-icon"><GitCompareArrows :size="19"/></span><div class="task-copy"><h3>{{t.title}}</h3><p><span>{{t.domain}}</span><span>{{t.crop}}</span><span>{{t.id}}</span></p></div><button class="outline small" @click="go('reviews');review(t)">开始评审</button></div><div v-if="!pending.length" class="empty-inline"><CheckCheck :size="26"/>暂无待处理的真实问题</div></div><div class="review-footer"><ShieldCheck :size="16"/>A/B 顺序由后端固定，人工提交前隐藏来源和裁判。</div></section>
     <section class="grow-card"><div class="grow-top"><span>AGRI LEARNING LOOP</span><Sprout :size="25"/></div><h2>把经验留下来，<br>让模型更懂农业。</h2><p>用经过专家审核的真实案例，<br>积累属于园区的专业知识。</p><div class="loop-steps"><span>提问</span><i></i><span>评审</span><i></i><span>样本</span><i></i><span>训练</span></div><button @click="go('reviews')">进入专家工作台 <ArrowUpRight :size="17"/></button></section>
     <section class="panel trend-panel"><div class="panel-heading"><div><h2>数据积累趋势</h2><p>标注与审核情况 · 演示图表</p></div><select v-model="period" aria-label="趋势时间范围"><option>近 7 天</option><option>近 30 天</option></select></div><div class="chart-legend"><span><i class="green-dot"></i>已标注</span><span><i class="gray-dot"></i>已审核</span><span class="sample-label">示意数据</span></div><div class="chart" role="img" :aria-label="`${period}示意趋势图，非真实统计`"><div class="y-axis"><span>40</span><span>30</span><span>20</span><span>10</span><span>0</span></div><div class="plot"><div class="grid-lines"><i></i><i></i><i></i><i></i><i></i></div><svg viewBox="0 0 600 150" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#20875c" stop-opacity=".17"/><stop offset="100%" stop-color="#20875c" stop-opacity="0"/></linearGradient></defs><path :d="period==='近 7 天'?'M0 126 C45 127 65 105 100 108 S160 84 200 90 S265 112 300 73 S365 80 400 49 S465 63 500 31 S560 32 600 10 L600 150 L0 150Z':'M0 140 C90 138 80 90 150 105 S220 62 300 74 S390 35 450 44 S530 30 600 5 L600 150 L0 150Z'" fill="url(#area)"/><path d="M0 140 C45 135 65 127 100 130 S165 107 200 114 S260 109 300 102 S365 84 400 90 S465 70 500 77 S560 50 600 55" fill="none" stroke="#a5bdb4" stroke-width="2.5" stroke-dasharray="5 5"/><path :d="period==='近 7 天'?'M0 126 C45 127 65 105 100 108 S160 84 200 90 S265 112 300 73 S365 80 400 49 S465 63 500 31 S560 32 600 10':'M0 140 C90 138 80 90 150 105 S220 62 300 74 S390 35 450 44 S530 30 600 5'" fill="none" stroke="#21865d" stroke-width="3"/></svg><div class="x-axis"><span v-for="d in (period==='近 7 天'?['10/03','10/04','10/05','10/06','10/07','10/08','10/09']:['09/10','09/15','09/20','09/25','09/30','10/05','10/09'])">{{d}}</span></div></div></div></section>
     <section class="panel runtime-panel"><div class="panel-heading"><h2>模型服务</h2><button class="text-button" @click="loadModels">刷新 <RotateCcw :size="15"/></button></div><div v-for="m in modelStatus" :key="m.id" class="model-row"><span class="model-icon"><Cpu :size="22"/></span><div><strong>{{m.name}}</strong><small>{{m.note}}</small></div><span class="badge neutral">{{m.provider==='zhipu'?'云端':'本地'}}</span></div><p v-if="!modelStatus.length" class="runtime-note">尚未读取后端状态，请启动服务。</p><div class="runtime-note"><Server :size="17"/><div><strong>模型来源由后端记录</strong><p>密钥已配置不代表上游调用可用。</p></div></div></section>
    </div>
    <section class="panel activity-panel"><div class="panel-heading"><h2>最近动态</h2><span class="muted">本次演示会话</span></div><div class="activities"><div v-for="(e,i) in events.slice(0,3)" :key="i"><span class="activity-icon"><Check :size="15"/></span><div><strong>{{e.title}}</strong><p>{{e.detail}}</p></div><small>{{e.time}}</small></div></div></section>
   </template>

   <Pipeline v-else-if="route==='chat'||route==='reviews'" :key="route" :page="route" :initial-id="pipelinePairId" @changed="updateTasks"/>

   <template v-else-if="route==='knowledge'">
    <section class="page-heading"><div><div class="eyebrow">KNOWLEDGE LIBRARY</div><h1>知识资料</h1><p>有来源、可追溯的资料，是农业智能的基础。</p></div><button class="primary" @click="openDialog('upload')"><Upload :size="17"/>登记资料</button></section><div class="notice"><span><CircleAlert :size="16"/>演示版仅登记文件信息，不上传原文件，不执行解析、向量化或知识检索。</span></div><div class="knowledge-categories"><button v-for="(d,i) in ['全部','种植管理','农业物联网','农业销售']" :class="['category',{selected:filter===d}]" @click="filter=d"><component :is="[Library,Sprout,Cable,FileText][i]" :size="23"/><div><strong>{{d==='全部'?'全部资料':d}}</strong><span>{{d==='全部'?docs.length:docs.filter(x=>x.domain===d).length}} 份资料</span></div></button></div><section class="panel"><div class="panel-heading"><h2>资料列表</h2><label class="search"><Search :size="16"/><input v-model="query" placeholder="搜索资料名称" aria-label="搜索资料名称"/></label></div><div class="table-scroll"><table><thead><tr><th>资料名称</th><th>领域</th><th>状态</th><th>登记时间</th><th>操作</th></tr></thead><tbody><tr v-for="d in visibleDocs" :key="d.id"><td><div class="file-cell"><span :class="['file-icon',d.type.toLowerCase()]"><FileText :size="23"/></span><div><strong>{{d.name}}</strong><small>{{d.type}} · {{d.size}} · {{d.source}}</small></div></div></td><td>{{d.domain}}</td><td><span class="badge neutral">{{d.status}}</span></td><td>{{d.date}}</td><td><button class="text-button" @click="notify(d.status==='示例资料'?'这是示例目录，未附带真实文件':'文件只登记在本次会话，尚未上传到服务器')">查看信息<ChevronRight :size="15"/></button></td></tr><tr v-if="!visibleDocs.length"><td colspan="5" class="empty-cell">没有符合条件的资料</td></tr></tbody></table></div></section><div class="pipeline panel"><h3>知识入库流程</h3><div><span>原始资料</span><ChevronRight/><span>解析与清洗</span><ChevronRight/><span>专家审核</span><ChevronRight/><span>发布知识库</span></div><p>正式后端接入后，每个环节将保留来源、版本和审核记录。</p></div>
   </template>

   <template v-else-if="route==='training'">
    <section class="page-heading"><div><div class="eyebrow">MODEL DEVELOPMENT</div><h1>模型训练</h1><p>先形成高质量样本，再用评测验证每一次改进。</p></div><button class="outline" @click="exportData"><Download :size="17"/>查看正式数据集导出</button></section><div class="training-banner"><span class="training-mark"><Cpu :size="34"/></span><div><span class="badge light">等待设备接入</span><h2>你的农业模型，从这里开始成长。</h2><p>DGX Spark · 128GB 统一内存 · 4TB 存储（规划配置）</p></div><button class="light-button" @click="openDialog('training')">查看接入清单 <ChevronRight :size="16"/></button></div><div class="training-grid"><section class="panel"><div class="panel-heading"><h2>训练准备</h2><span class="badge amber">准备中</span></div><div class="checklist"><div><span class="check-circle done"><Check :size="15"/></span><div><strong>专家标注流程</strong><p>前端可体验选择、修订与复审</p></div></div><div><span class="check-circle">2</span><div><strong>积累真实农业样本</strong><p>当前 {{checked.length}} 条复审记录，导出时隔离评测组</p></div></div><div><span class="check-circle">3</span><div><strong>确认同源训练权重</strong><p>部署量化包不等同于已验证训练底座</p></div></div><div><span class="check-circle">4</span><div><strong>连接 DGX 与评测服务</strong><p>尚未发起任何实际训练</p></div></div></div></section><section class="panel"><div class="panel-heading"><h2>模型版本</h2><span class="muted">尚无发布版本</span></div><div class="model-empty"><FlaskConical :size="38"/><h3>等待第一轮训练</h3><p>完成数据审核、训练与独立评测后，<br>候选版本将出现在这里。</p><button class="outline" @click="go('reviews')">前往专家评审</button></div></section></div><section class="panel pipeline"><h3>每次进步，都有迹可循</h3><div><span>数据集版本</span><ChevronRight/><span>LoRA 微调</span><ChevronRight/><span>独立评测</span><ChevronRight/><span>审核发布</span></div><p>保留模型、数据、提示词、技能和策略版本，支持回退到稳定版本。</p></section>
   </template>

   <template v-else-if="route==='gateway'">
    <section class="page-heading"><div><div class="eyebrow">MODEL GATEWAY</div><h1>模型中转</h1><p>本地模型与云端服务使用统一入口，业务流程不绑定供应商。</p></div><button class="outline" @click="exportConfig"><Download :size="17"/>导出配置草稿</button></section><div class="notice"><span><ShieldCheck :size="16"/>此页面只编辑配置草稿，不直接连接供应商。API 密钥应在后端环境变量中配置。</span></div><div class="gateway-grid"><section class="panel"><div class="panel-heading"><h2><Cpu :size="20"/> 本地农业模型</h2><span class="badge neutral">待接入</span></div><div class="model-detail"><span class="model-monogram">Q</span><h3>{{modelStatus.find(m=>m.id==='local_agri')?.name||'本地模型待读取'}}</h3><p>当前通过 Ollama；27B 为后续 DGX 部署候选</p></div><dl class="spec-list"><div><dt>逻辑名称</dt><dd>local_agri</dd></div><div><dt>计算设备</dt><dd>当前本机 / 后续 DGX Spark</dd></div><div><dt>系统环境</dt><dd>DGX OS / Ubuntu · ARM64</dd></div><div><dt>推理服务</dt><dd>待验证 Ollama / vLLM</dd></div><div><dt>当前连接</dt><dd>{{modelStatus.find(m=>m.id==='local_agri')?.note||'未读取'}}</dd></div></dl><button class="outline full" @click="openDialog('training')">查看本地接入说明</button></section><section class="panel gateway-form"><div class="panel-heading"><h2><Network :size="20"/> 云端模型</h2><span class="badge neutral">{{settingsSaved?'草稿已保存':'未配置'}}</span></div><form @submit.prevent="saveConfig"><label>协议适配器<select v-model="provider" @change="settingsSaved=false"><option>兼容接口</option><option>供应商原生接口</option></select></label><label>API 基础地址<input v-model="baseUrl" @input="settingsSaved=false" placeholder="https://your-provider.example/v1" type="url" required/></label><label>模型名称<input v-model="modelName" @input="settingsSaved=false" placeholder="填写供应商提供的模型名称" required maxlength="150"/></label><label>密钥环境变量<input value="CLOUD_PRIMARY_API_KEY" readonly/><small>不在浏览器输入或保存真实密钥。</small></label><p v-if="settingsError" class="error-text" role="alert">{{settingsError}}</p><button class="primary full" type="submit">校验并保存草稿</button></form></section></div><section class="panel pipeline"><h3>统一调用路径</h3><div><span>农业工作台 / Hermes</span><ChevronRight/><span>策略与权限</span><ChevronRight/><span>模型网关</span><ChevronRight/><span>本地 / 云端</span></div><p>供应商故障需明确记录；双模型评审不静默替换模型来源。</p></section>
   </template>
   <footer class="page-footer"><span><Sprout :size="14"/> 青禾 · 农业 AI 工作台</span><span>本地部署优先 <i>·</i> 本地工作台 v0.2</span></footer>
  </main>
 </div>
 <Transition name="toast"><div v-if="toast" class="toast-message" role="status"><Check :size="18"/>{{toast}}</div></Transition>
 <div v-if="dialog" class="modal-backdrop" @click.self="dialog=''"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-heading"><h2 id="modal-title">{{({upload:'登记农业资料',help:'当前版本说明',workspace:'农业 AI 工作空间',notifications:'工作空间通知',training:'DGX 接入清单'})[dialog]}}</h2><button aria-label="关闭弹窗" @click="dialog=''"><X :size="21"/></button></div>
  <template v-if="dialog==='upload'"><p>演示版仅保存本次会话的文件信息，文件不会上传到服务器。</p><button class="upload-zone" @click="fileInput.click()"><Upload :size="30"/><strong>选择本地资料</strong><span>PDF、DOCX、TXT · 单个文件不超过 20 MB</span></button><input ref="fileInput" type="file" multiple accept=".pdf,.docx,.txt" hidden @change="handleFiles"/><ul v-if="uploadFiles.length" class="file-selection"><li v-for="f in uploadFiles" :key="f.name"><FileText :size="16"/>{{f.name}}</li></ul><label>资料领域<select v-model="uploadDomain"><option>种植管理</option><option>农业物联网</option><option>农业销售</option></select></label><p v-if="uploadError" class="error-text" role="alert">{{uploadError}}</p><div class="modal-footer"><button class="outline" @click="dialog=''">取消</button><button class="primary" @click="registerFiles">登记文件信息</button></div></template>
  <template v-else-if="dialog==='help'"><p>这是农业 AI 平台的首版 本地数据工作台，所有状态仅保留在当前页面会话，刷新即重置。</p><ul class="readable-list"><li>可操作：真实双模型问答、独立盲评、专家修订、复审、SFT / DPO / 评测集导出。</li><li>模型通过后端配置连接；Hermes、文件上传、知识检索及 DGX 训练尚未接入。</li><li>当前身份是演示身份，尚未实现登录与多用户权限。</li><li>正式部署前将接入业务后端；模型密钥不进入前端。</li></ul></template>
  <template v-else-if="dialog==='workspace'"><div class="workspace-large"><span class="brand-mark"><Sprout :size="28"/></span><div><h3>农业 AI 工作空间</h3><p>208 亩示范园区 · 首期 AI 数据闭环</p></div></div><p>当前为演示管理员身份。园区采集、设备控制与机器人平台尚未连接。后续通过受控接口接入，数据按租户和园区隔离。</p></template>
  <template v-else-if="dialog==='notifications'"><div class="notification-entry" v-for="e in events.slice(0,5)"><Activity :size="18"/><div><strong>{{e.title}}</strong><p>{{e.detail}}</p></div></div></template>
  <template v-else-if="dialog==='training'"><p>当前已提供数据后端；不会执行真实训练或修改设备。</p><ol class="readable-list"><li>在 DGX OS 上部署 ARM64 兼容的业务后端与数据库。</li><li>验证本地千问推理、上下文长度和工具调用。</li><li>确认同源、适合微调的权重及训练框架。</li><li>导入审核过的真实农业数据，保留独立测试集。</li><li>训练与推理错峰运行，完成评测后再发布版本。</li></ol></template>
 </section></div>
</div>
</template>
