<script setup>
import {ref,computed,onMounted,onUnmounted,watch} from 'vue';
import {Plus,Download,ShieldCheck,Clock3,ChevronRight,RefreshCw,Check,Database,Send} from 'lucide-vue-next';
import {api} from './api';
const props=defineProps({page:String,initialId:String});
const emit=defineEmits(['changed']);
const rows=ref([]),activeId=ref(props.initialId||''),question=ref(''),filter=ref('全部'),actor=ref(''),reviewer=ref('');
const answer=ref(''),evidence=ref(''),notes=ref(''),preferred=ref(''),acceptable=ref(false),error=ref(''),notice=ref(''),working=ref(false),loaded=ref(false);
const requestDraft=ref(null);let poll,stopped=false,formKey='',refreshing=false;
const active=computed(()=>rows.value.find(r=>r.id===activeId.value));
const labels={unreviewed:'待盲评',pending:'待修订',awaiting_review:'待复审',approved:'已审核',excluded:'已排除'};
const choiceLabels={A:'A 更好',B:'B 更好',tie:'两者相当',both_bad:'两者都不好',insufficient:'信息不足'};
const generationLabels={generating:'生成中',completed:'已完成',partial:'单路可用',failed:'生成失败'};
const visible=computed(()=>rows.value.filter(r=>filter.value==='全部'||r.review_status===filter.value));
const locked=computed(()=>['approved','excluded'].includes(active.value?.review_status));
const statusErrorLabels={rate_limited:'供应商限流',timeout:'上游超时',invalid_output:'评分格式错误',configuration:'配置错误',upstream_error:'上游调用失败'};
function source(c){if(!c.model)return '未生成 · 无有效来源';return `${c.provider==='local'||c.provider==='local2'?'本地':'云端'} · ${c.model}`}
function syncForm(){const r=active.value,key=`${r?.id}:${r?.expert?.revision||0}`;if(key===formKey)return;formKey=key;answer.value=r?.expert?.answer||'';evidence.value=r?.expert?.evidence||'';notes.value=r?.expert?.notes||'';preferred.value=r?.approval?.preferred||'';acceptable.value=Boolean(r?.approval?.original_acceptable)}
async function refresh(){if(refreshing)return;refreshing=true;try{const out=await api.comparisons();if(stopped)return;rows.value=out.items;loaded.value=true;syncForm();emit('changed',rows.value)}catch(e){if(!stopped)error.value=e.message}finally{refreshing=false}}
function select(r){activeId.value=r.id;error.value='';notice.value='';syncForm()}
function newQuestion(){activeId.value='';question.value='';requestDraft.value=null;formKey='';error.value='';notice.value=''}
async function action(fn){if(working.value)return;working.value=true;error.value='';notice.value='';try{await fn();await refresh()}catch(e){error.value=e.message}finally{working.value=false}}
async function submit(){if(!question.value.trim())return;await action(async()=>{if(!requestDraft.value||requestDraft.value.question!==question.value.trim())requestDraft.value={question:question.value.trim(),request_id:crypto.randomUUID()};const r=await api.createComparison(requestDraft.value);activeId.value=r.id;question.value='';requestDraft.value=null;notice.value='任务已保存，可刷新或离开页面；生成由后端继续执行。'})}
async function choose(choice){await action(async()=>{await api.choose(active.value.id,{choice,actor:actor.value});notice.value='独立判断已保存，现可查看真实来源与后续裁判意见。'})}
async function revise(){await action(async()=>{await api.revise(active.value.id,{answer:answer.value,evidence:evidence.value,notes:notes.value,actor:actor.value,revision:active.value.expert?.revision});notice.value='修订已保存，等待另一位同事复审。'})}
async function approve(){await action(async()=>{await api.approve(active.value.id,{actor:reviewer.value,revision:active.value.expert.revision,preferred:preferred.value||null,original_acceptable:acceptable.value});notice.value='复审通过。SFT 与 DPO 按不同准入条件导出。'})}
async function exclude(){await action(async()=>{await api.exclude(active.value.id,{actor:actor.value,reason:notes.value});notice.value='已保留记录并排除训练。'})}
async function exportSet(kind){await action(async()=>{const out=await api.exportDataset(kind);const url=URL.createObjectURL(new Blob([out.items.map(x=>JSON.stringify(x)).join('\n')],{type:'application/jsonl'}));const a=document.createElement('a');a.href=url;a.download=`agri-${kind}-${out.id}.jsonl`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice.value=`已导出 ${out.items.length} 条；版本快照 ${out.id.slice(0,8)} 已保存在数据库。`})}
watch(()=>props.initialId,id=>{if(id){activeId.value=id;syncForm()}});
watch(()=>props.page,()=>{if(props.page==='reviews'&&!props.initialId)activeId.value=''});
onMounted(async()=>{await refresh();if(!stopped)poll=setInterval(refresh,2500)});
onUnmounted(()=>{stopped=true;clearInterval(poll)});
</script>

<template>
 <section class="page-heading"><div><div class="eyebrow">AGRICULTURAL EXPERT DATA</div><h1>{{page==='chat'?'农业问答 · 独立盲评':'专家数据工作台'}}</h1><p>先独立判断，再查看裁判；先审核标准答案，再沉淀训练数据。</p></div><button class="primary" @click="newQuestion" v-if="page==='chat'"><Plus :size="17"/>新问题</button><button class="outline" @click="refresh" v-else><RefreshCw :size="16"/>刷新</button></section>
 <div class="notice"><span><Database :size="17"/>问答、评审与导出快照已由本地数据库保存。资料登记仍是演示功能；当前仅限本机试用，姓名为人工填写而非登录认证。</span></div>
 <p v-if="error" class="pipeline-error" role="alert">{{error}}<button @click="error='';refresh()">重新读取</button></p>
 <p v-if="notice" class="pipeline-success" role="status">{{notice}}</p>
 <div v-if="page==='reviews'" class="dataset-actions"><button class="outline" :disabled="working" @click="exportSet('sft')"><Download :size="16"/>导出已复审 SFT</button><button class="outline" :disabled="working" @click="exportSet('dpo')"><Download :size="16"/>导出合格 DPO</button><button class="outline" :disabled="working" @click="exportSet('eval')"><Download :size="16"/>导出独立评测集</button><span>评测组永不进入训练导出</span></div>
 <section v-if="page==='chat'&&!active" class="panel review-form"><h2>提出一个需要专业判断的问题</h2><p class="pipeline-caption">每个问题独立生成，不混入前面两路回答。请将必要背景写在问题里。</p><form @submit.prevent="submit"><label>问题与农业背景<textarea v-model="question" maxlength="4000" rows="5" placeholder="例如：番茄处于开花期，基质栽培。请列出调整灌溉前需要核实的条件。" required/></label><div class="form-footer"><span class="muted">真实模型由后端配置；同一问题的 A/B 顺序固定。</span><button class="primary" :disabled="working||!question.trim()"><Send :size="16"/>生成双路回答</button></div></form></section>
 <template v-if="active">
  <button class="text-button back" @click="activeId=''">返回记录列表</button>
  <section class="panel question-panel"><div><span class="badge neutral">{{generationLabels[active.status]}}</span><span class="badge" :class="active.split==='eval'?'amber':'success'">{{active.split==='eval'?'独立评测组 · 不用于训练':'训练候选组'}}</span><span class="muted">{{active.id.slice(0,8)}} · {{labels[active.review_status]}}</span></div><h2>{{active.question}}</h2><p>相同规范化问题固定分组；近似问题仍需在正式训练前按来源复核去重。</p></section>
  <div class="answer-grid"><article v-for="c in active.candidates" :key="c.label" class="panel answer-card"><div class="panel-heading"><h3><span class="answer-letter">{{c.label}}</span>候选回答 {{c.label}}</h3><span class="badge neutral">{{active.choice?source(c):'来源隐藏'}}</span></div><div v-if="c.status==='pending'" class="answer-text"><Clock3 :size="18"/> 等待生成，本地模型按队列执行。</div><div v-else-if="c.status==='failed'" class="answer-text error-text">{{c.error}}</div><div v-else class="answer-text">{{c.text}}</div><button v-if="active.choice&&c.status==='completed'&&!locked" class="text-button" @click="answer=c.text;notice='已复制至标准答案，请核实并修订。'">以 {{c.label}} 为基础修订</button></article></div>
  <section v-if="!active.choice" class="panel review-form"><h2>你的独立判断</h2><p class="pipeline-caption">提交前不展示裁判结果、相似度或来源。两者都不好时不要强行选优。</p><label>标注人姓名<input v-model="actor" maxlength="80" placeholder="填写真实姓名，便于追溯"/></label><div class="choice-row"><button v-for="(label,value) in choiceLabels" :key="value" class="choice" :disabled="working||!actor.trim()||active.status==='generating'||(active.status!=='completed'&&value!=='insufficient')" @click="choose(value)">{{label}}</button></div></section>
  <template v-else>
   <section class="panel judge-card"><h3>已提交判断：{{choiceLabels[active.choice.value]}} <span class="muted">{{active.choice.actor}}</span></h3><div class="choice-row"><span class="badge amber" v-for="tag in active.priority">{{tag}}</span><span v-if="active.similarity" class="badge neutral">字符相似度 {{active.similarity.score.toFixed(2)}} · 仅作线索</span></div><p v-if="active.judge.status==='completed'">AI 裁判：{{active.judge.result.winner==='tie'?'两者相当':active.judge.result.winner+' 更好'}} · A {{active.judge.result.score_a}} / B {{active.judge.result.score_b}}<br>{{active.judge.result.reason}}<br><span class="muted">实际裁判：{{active.judge.result.judge_model}}（{{active.judge.result.provider}}）。同模型自评可能有偏差，仅作辅助。</span></p><p v-else-if="active.judge.status==='failed'">裁判未完成：{{statusErrorLabels[active.judge.error.code]}}。不影响专家修订，不能视作评分。<small>{{active.judge.error.message}}</small></p><p v-else-if="active.judge.status==='unavailable'">回答不完整，本条不进行 AI 对比评分。</p><p v-else>裁判任务已排队，稍后结果会回写到本条记录，刷新或切换页面不会丢失。</p></section>
   <section class="panel review-form"><h2>专家修订与依据</h2><label>修订人姓名<input v-model="actor" :disabled="locked" placeholder="复审需由另一位同事完成" maxlength="80"/></label><label>专家标准答案<textarea v-model="answer" :readonly="locked" rows="6" placeholder="给出经过核实的答案，或准确说明缺少哪些必要条件。"/></label><label>依据与适用条件<textarea v-model="evidence" :readonly="locked" rows="3" placeholder="记录资料来源、检测依据、作物阶段和适用边界；不要编造引用。"/></label><label>优化建议 / 排除原因<textarea v-model="notes" :readonly="locked" rows="2"/></label><div class="form-footer"><span class="muted">{{active.expert?'已保存修订 v'+active.expert.revision+' · '+active.expert.actor:'尚未提交修订'}}</span><div v-if="!locked"><button class="outline" :disabled="working||!actor.trim()||!notes.trim()" @click="exclude">排除训练，保留记录</button><button class="primary" :disabled="working||!actor.trim()||!answer.trim()||!evidence.trim()" @click="revise">保存并提交复审</button></div><span v-else class="badge success">{{labels[active.review_status]}} · 只读</span></div></section>
   <section v-if="active.review_status==='awaiting_review'" class="panel review-form"><h2>独立复审</h2><p class="pipeline-caption">复审基于已保存的修订，不包含尚未保存的编辑。SFT 使用专家答案；DPO 只使用经确认合格的原始回答对。</p><label>复审人姓名<input v-model="reviewer" maxlength="80" placeholder="应不同于标注人与修订人"/></label><label>原始回答偏好确认<select v-model="preferred"><option value="">仅通过标准答案，不生成 DPO</option><template v-if="['A','B'].includes(active.choice.value)&&active.status==='completed'"><option value="A">原始 A 合格且优于 B</option><option value="B">原始 B 合格且优于 A</option></template></select></label><label class="checkbox-label" v-if="preferred"><input type="checkbox" v-model="acceptable"/>我已核实所选原始回答本身合格，修订答案更好不代表原回答合格。</label><button class="primary" :disabled="working||!reviewer.trim()||(!!preferred&&!acceptable)" @click="approve"><Check :size="16"/>审核通过已保存版本</button></section>
   <section v-if="active.approval" class="panel judge-card"><h3>复审记录</h3><p>{{active.approval.actor}} · 修订 v{{active.approval.revision}} · {{new Date(active.approval.at).toLocaleString()}}<br>{{active.approval.preferred?'DPO 原始偏好：'+active.approval.preferred:'仅标准答案通过；无 DPO 偏好'}}<br>{{active.split==='eval'?'本条只进入独立评测导出，不进入 SFT / DPO。':'本条可按审核结果进入训练导出。'}}</p></section>
  </template>
 </template>
 <section v-if="!active" class="panel persistent-list"><div class="panel-heading"><h2>{{page==='chat'?'已保存的问题':'评审队列'}}</h2><select v-model="filter" aria-label="按状态筛选"><option value="全部">全部状态</option><option v-for="(text,value) in labels" :value="value">{{text}}</option></select></div><div class="table-scroll"><table><thead><tr><th>问题</th><th>状态</th><th>分组</th><th>优先线索</th><th>操作</th></tr></thead><tbody><tr v-for="r in visible" :key="r.id"><td><strong>{{r.question.slice(0,45)}}</strong><small>{{r.id.slice(0,8)}} · {{new Date(r.created_at).toLocaleString()}}</small></td><td>{{labels[r.review_status]}}<small>{{generationLabels[r.status]}}</small></td><td>{{r.split==='eval'?'独立评测':'训练候选'}}</td><td>{{r.priority.join('、')||'常规评审'}}</td><td><button class="text-button" @click="select(r)">打开 <ChevronRight :size="15"/></button></td></tr><tr v-if="!visible.length"><td colspan="5" class="empty-cell">{{loaded?'暂无真实记录。提出问题后会自动保存。':'正在连接本地数据库…'}}</td></tr></tbody></table></div></section>
</template>

<style scoped>
.pipeline-caption{color:#71816e;font-size:14px;margin:14px 0;line-height:1.9}.pipeline-error,.pipeline-success{padding:15px 18px;border-radius:8px;margin:16px 0;line-height:1.7}.pipeline-error{background:#fff0e9;color:#944a33;display:flex;justify-content:space-between;gap:10px}.pipeline-error button{white-space:nowrap}.pipeline-success{background:#eaf5e8;color:#426935}.dataset-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:20px 0}.dataset-actions>span{font-size:12px;color:#7b896f}.judge-card{padding:22px;margin:20px 0}.judge-card p{font-size:14px;margin-top:15px}.judge-card small{display:block;overflow-wrap:anywhere}.persistent-list{margin-top:22px}.review-form{margin:20px 0}.checkbox-label{display:flex;align-items:flex-start;gap:10px;line-height:1.8}.checkbox-label input{width:18px;flex-shrink:0;margin-top:4px}.answer-text{overflow-wrap:anywhere;max-height:650px;overflow:auto}.question-panel h2{white-space:pre-wrap;overflow-wrap:anywhere}.answer-card .panel-heading{flex-wrap:wrap}.answer-card .badge{overflow-wrap:anywhere;max-width:100%}.answer-grid{align-items:stretch}.form-footer{flex-wrap:wrap}input:disabled{opacity:.65}table td:first-child{white-space:normal;min-width:220px;max-width:400px;overflow-wrap:anywhere}
</style>
